# Generated by Django 4.1.4 on 2023-04-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='topic1',
        ),
    ]
