# Generated by Django 4.1.4 on 2023-04-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_topic_topic1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='topic1',
            new_name='Topic',
        ),
    ]
